import 'package:get/get.dart';

class MyLocal implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "phone_number": "رقم الهاتف",
          "password": "كلمة المرور",
          "error": "خطأ",
          "wrongBossID": "رقم قائد الفريق غير صحيح",
          "unit": "وحدة",
          "requiredField": "هذا الحقل إلزامي",
          "emailExist": "هذا البريد الإلكتروني موجود بالفعل",
          "createAccount": "إنشاء حساب",
          "phoneNoExist": "هذا الرقم مسجل مسبقاً",
          "wrongLogin": "رقم الهاتف أو كلمة المرور غير صحيحة",
          "language": "اللغة",
          "edit": "معلومات الحساب",
          "withdraw": "سحب",
          "deposit": "إيداع",
          "team": "الفريق",
          "total_personal_income": "إجمالي الدخل الشخصي",
          "total_team_income": "إجمالي دخل الفريق",
          "daily_personal_income": "الدخل الشخصي اليومي",
          "quantifying_count": "عدد التكميم",
          "daily_income": "الدخل اليومي",
          "daily_team_income": "الدخل اليومي للفريق",
          "ref_link": "رابط الإحالة",
          "your_name": "اسمك",
          "wallet_address": "عنوان المحفظة",
          "witdraw_pass": "كلمة المرور للسحب",
          "email": "البريد الإلكتروني",
          "pass": "كلمة المرور",
          "phone": "رقم الهاتف",
          "loading...": "جار التحميل...",
          "note_link_expire": "ملاحظة: الرابط تنتهي صلاحيته خلال ساعه",
          "qqxxafrgthbghuuuseee": "المبلغ",
          "deposit_amount": "المبلغ المراد إيداعه",
          "confirm_deposit": "تأكيد الإيداع",
          "edit_account": "معلومات الحساب",
          "quan4": "جاري حسب النسبه المستحقة",
          "reports": "التقارير",
          "choose_report": "اختر التقرير",
          "start_exchange": "بدء التداول",
          "trading_in_progress": "جاري عملية البيع ",
          "searching_for_buy_deal": "جاري بدأ عمليه التداول  ",
          "opening_buy_deal": "جاري إلتقاط أسعار السوق ",
          "closing_buy_deal": "جاري عمليه الشراء ",
          "notes": "ملاحظات",
          "withdraw_process_note": "سوف تتم عملية السحب خلال 72 ساعة",
          "withdraw_commission_note": "سوف يتم خصم مبلغ 2% لعمولة السحب",
          "withdraw_password": "كلمة مرور السحب",
          "debit_amount": "مبلغ الايداع",
          "debit_amount_less": " مبلغ الايداع يجب ان يكون اكبر من 50 دولار",
          "balance": "الرصيد",
          "team1": " عدد الفريق الاول ",
          "team2": "عدد الفريق الثاني ",
          "team3": "عدد الفريق الثالث ",
          "success": " تم بنجاح",
          "success_deposit": " عملية الايداع تمت بنجاح ",
          "depoist_null_wallet_address": "يرجى انشاء عنوان محفظة",
          "already_have_wallet_address": "أنت بالفعل لديك عنوان محفظة",
          "not_same_withdraw_pass": "كلمه المرور غير صحيحه",
          "team_info": "معلومات الفريق",
          "coin_name": "الأسم",
          "coin_price": "السعر الحالي",
          "change": "التغير",
          "settings": "الإعدادات",
          "exit": "تسجيل الخروج",
          "sign_up": "إنشاء حساب",
          "forget_password": "نسيان كلمة المرور",
          "create_account": "إنشاء حساب",
          "withdraw_amount": "مبلغ السحب",
          "amount": "المبلغ",
          "confirm_cancel": "تأكيد الإلغاء",
          "sure_cancel": "هل تود بالفعل إلغاء العملية؟",
          "yes": "نعم",
          "no": "لا",
          "Text_copied": "تم نسخ العنوان",
          "cancel": "إلغاء",
          "withrdraw_greatter_than_balance": "عذرا رصيدك غير كافي",
          "success_account_edit": "تم تعديل الحساب بنجاح",
          "please_wait": "يرجى الإنتظار",
          "you_can_press_5_each_30":
              "المعذرة يمكنك فقط التداول كل 30 ثانية, خمس مرات في اليوم فقط",
          "about": "من نحن",
          "make_world_better": "جعل العالم يعمل بشكل افضل للجميع",
          "cardano_description":
              "Cardano هي عبارة عن منصة blockchain لصانعي التغيير والمبتكرين وأصحاب الرؤى، مع الأدوات والتقنيات اللازمة لخلق الإمكانية للكثيرين، فضلاً عن القلة، وإحداث تغيير عالمي إيجابي. أول منصة blockchain يتم تأسيسها على أساس مراجعة النظراء البحث والتطوير من خلال الأساليب القائمة على الأدلة. فهو يجمع بين التقنيات الرائدة لتوفير أمان واستدامة لا مثيل لهما للتطبيقات والأنظمة والمجتمعات اللامركزية.",
          "leading_team_description":
              "مع فريق رائد من المهندسين، تهدف كاردانو إلى إعادة توزيع السلطة من الهياكل غير الخاضعة للمساءلة إلى الهوامش - للأفراد - وتكون قوة تمكينية للتغيير الإيجابي والتقدم.",
          "you_can_press_5_each_day":
              "لقد تجاوزت الحد المسموح به للتكميم خلال اليوم",
          "important_notes": ":ملاحظات مهمه",
          "important_notes1": " 1- عنوان المحفظة متاح لمدة ساعه فقط. ",
          "important_notes2": "2-الحد الأدنى لمبلغ السحب هو 50 USDT.",
          "important_notes3":
              "3- اذا تم ايداع المبلغ ولم يصلك يرجى التواصل مع فريق الدعم.",
          "withdraw_amount_minimum": "الحد الأدنى لمبلغ السحب هو 50 USDT",
          "withdraw_operations": "عمليات السحب",
          "deposit_operations": "عمليات الإيداع",
          "are_you_sure_to_close": "هل تريد بالفعل إغلاق التطبيق؟",
          "confirm_exit": "تأكيد الإغلاق",
          "successful": "ناجحة",
          "rejected": "مرفوضة",
          "canceled": "ملغية",
          "processing": "جاري المعالجة",
          "success_withdraw": "عملية السحب تمت بنجاح",
          "not_allowed_to_quantifying":
              "رصيدك الحالي اقل من 50\$, ليس ممكن لك بالتداول",
          "not_device": "الجهاز الحالي ليش الجهاز الذي تم انشاء الحساب عبرة..",
          "withrdraw_less_than_50": "مبلغ السحب يجب ان يكون اكبر من 50 \$",
          "help_support": "الدعم الفني"
        },
        "en": {
          "phone_number": "Phone Number",
          "reports": "reports",
          "withrdraw_less_than_50": "the amount should be greater than 50\$",
          "not_device":
              "this device is not the same device you have created the account with..",
          "not_allowed_to_quantifying":
              "your are not allowed to quantifying, your balabnce is less 50\$",
          "password": "Password",
          "withdraw_amount_minimum": "The minimum withdrawal amount is 50 USDT",
          "important_notes": "Important Notes:",
          "important_notes1":
              "1- The wallet address is available for one hour only.",
          "important_notes2": "2- The minimum withdrawal amount is 50 USDT.",
          "important_notes3":
              "3- If the amount has been deposited and you have not received it, please contact the support team.",
          "you_can_press_5_each_day":
              "you have exceed the number of quantifying per a day",
          "quantifying_count": "quantifying counts",
          "error": "error",
          "quan4": "Current according to the due percentage",
          "wrongBossID": "the team leader ID is wrong",
          "requiredField": "this field is required",
          "emailExist": "this email is already exist",
          "createAccount": "create account",
          "phoneNoExist": "this phone number is already exist",
          "wrongLogin": "wrong phone number or password",
          "language": "Language",
          "edit": "Account Info",
          "withdraw": "Withdraw",
          "deposit": "Deposit",
          "total_personal_income": "Total Personal Income",
          "total_team_income": "Total Team Income",
          "daily_personal_income": "Daily Personal Income",
          "daily_income": "Daily Income",
          "daily_team_income": "Daily Team Income",
          "ref_link": "Referral Link",
          "your_name": "Your Name",
          "wallet_address": "Wallet Address (Trc20)",
          "witdraw_pass": "Withdrawal Password",
          "email": "Email",
          "pass": "Password",
          "phone": "Phone",
          "loading...": "Loading...",
          "note_link_expire": "Note: The link expires within an hours",
          "qqxxafrgthbghuuuseee": "Amount",
          "deposit_amount": "Amount to Deposit",
          "confirm_deposit": "Confirm Deposit",
          "edit_account": " Account Info",
          "choose_report": "Choose Report",
          "start_exchange": "Start Exchange",
          "trading_in_progress": " Sale is in progress ",
          "searching_for_buy_deal": "The trading process has begun",
          "opening_buy_deal": "Capturing market prices",
          "closing_buy_deal": " Purchase in progress ",
          "team": "Team",
          "team_info": "Team Information",
          "team_count": "Team Count",
          "notes": "Notes",
          "withdraw_process_note":
              "Withdrawal process will take up to 72 hours",
          "withdraw_commission_note":
              "A 2% commission fee will be deducted for withdrawal",
          "withdraw_password": "Withdrawal Password",
          "debit_amount": "deposit amount",
          "debit_amount_less": " the deposit amount should be creater than 50",
          "balance": "Balance",
          "team1": "Team One Number ",
          "team2": "Team Tow Number ",
          "team3": "Team Three Number ",
          "success": "success ",
          "success_deposit": " the deposit order done successfully ",
          "depoist_null_wallet_address": "please generate a wallet address",
          "already_have_wallet_address": "you already have a wallet address",
          "not_same_withdraw_pass": "wrong pasword   ",
          "coin_name": "Name",
          "coin_price": "Current Price",
          "change": "Change",
          "settings": "Settings",
          "exit": "Logout",
          "sign_up": "Sign Up",
          "forget_password": "Forget Password",
          "create_account": "Create Account",
          "withdraw_amount": "Withdraw Amount",
          "amount": "Amount",
          "confirm_cancel": "Confirm Cancellation",
          "sure_cancel": "Are you sure you want to cancel?",
          "yes": "Yes",
          "no": "No",
          "cancel": "Cancel",
          "withrdraw_greatter_than_balance":
              "the amount is greater than your balance",
          "success_account_edit": "the account is edited ",
          "please_wait": "Please wait",
          "you_can_press_5_each_30":
              "Sorry you can exchange only each 30 seconds for 5 times a day",
          "about": "About us",
          "Text_copied": "Text copied",
          "make_world_better": "Make the world works better for everyone",
          "cardano_description":
              "Cardano is a blockchain platform for changemakers, innovators, and visionaries, with the tools and technologies required to create possibility for the many, as well as the few, and bring about positive global change. It is the first platform blockchain to be founded on peer-reviewed research and developed through evidence-based methods. It combines pioneering technologies to provide unparalleled security and sustainability to decentralized applications, systems, and societies.",
          "leading_team_description":
              "With a leading team of engineers, Cardano exists to redistribute power from unaccountable structures to the margins – to individuals – and be an enabling force for positive change and progress.",
          "login": "Login",
          "are_you_sure_to_close": "Are you sure you want to close the app?",
          "confirm_exit": "Confirm Exit",
          "successful": "Successful",
          "rejected": "Rejected",
          "canceled": "Canceled",
          "processing": "Processing",
          "success_withdraw": "the withdraw order done successfully ",
          "help_support": "Help and Support"
        }
      };
}
