part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();

  static const LOGIN = _Paths.LOGIN;
  static const DEPTMANAGEMENT = _Paths.DEPTMANAGEMENT;
  static const DEPTMANAG = _Paths.DEPTMANAG;
  static const STORESLIST = _Paths.STORESLIST;
  static const STOREDETAILS = _Paths.STOREDETAILS;
  static const ONBOARDING = _Paths.ONBOARDING;
  static const CHOOSEACCOUNT = _Paths.CHOOSEACCOUNT;
  static const MERCHANTAUTHSCREEN = _Paths.MERCHANTAUTHSCREEN;
  static const USERAUTHSCREEN = _Paths.USERAUTHSCREEN;
  static const MANAGECREDITORS = _Paths.MANAGECREDITORS;
  static const EPAYMENT = _Paths.EPAYMENT;
  static const MERCHANTHOME = _Paths.MERCHANTHOME;
  static const CUSTOMERSMANAGEMENT = _Paths.CUSTOMERSMANAGEMENT;
  static const ADDCUSTOMERSCREEN = _Paths.ADDCUSTOMERSCREEN;
  static const ADDDEPTSCREEN = _Paths.ADDDEPTSCREEN;
  static const EDITCUSTOMERSCREEN = _Paths.EDITCUSTOMERSCREEN;
  static const USERHOMESCREEN = _Paths.USERHOMESCREEN;
  static const CHOOSEREPORTSCREEN = _Paths.CHOOSEREPORTSCREEN;
  static const FINANCIALREPORTSCREEN = _Paths.FINANCIALREPORTSCREEN;
  static const MERCHANTREGISTERACCOUNT = _Paths.MERCHANTREGISTERACCOUNT;
  static const STOREORDERCREEN = _Paths.STOREORDERCREEN;
  static const DEBTDETAILSSCREEN = _Paths.DEBTDETAILSSCREEN;
  static const STOREFINREPORTSCREEN = _Paths.STOREFINREPORTSCREEN;
  static const STOREREPORTSSCREEN = _Paths.STOREREPORTSSCREEN;
  static const WALLETMANAGEMENT = _Paths.WALLETMANAGEMENT;
  static const ADDWALLET = _Paths.ADDWALLET;
}

abstract class _Paths {
  static const LOGIN = '/LOGIN';
  static const DEPTMANAGEMENT = '/DEPTMANAGEMENT';
  static const DEPTMANAG = '/DEPTMANAG';
  static const STORESLIST = '/STORESLIST';
  static const STOREDETAILS = '/STOREDETAILS';
  static const ONBOARDING = '/ONBOARDING';
  static const CHOOSEACCOUNT = '/CHOOSEACCOUNT';
  static const MERCHANTAUTHSCREEN = '/MERCHANTAUTHSCREEN';
  static const USERAUTHSCREEN = '/USERAUTHSCREEN';
  static const STOREORDERCREEN = '/STOREORDERCREEN';
  static const MANAGECREDITORS = '/MANAGECREDITORS';
  static const EPAYMENT = '/EPAYMENT';
  static const MERCHANTHOME = '/MERCHANTHOME';
  static const CUSTOMERSMANAGEMENT = '/CUSTOMERSMANAGEMENT';
  static const ADDCUSTOMERSCREEN = '/ADDCUSTOMERSCREEN';
  static const ADDDEPTSCREEN = '/ADDDEPTSCREEN';
  static const EDITCUSTOMERSCREEN = '/EDITCUSTOMERSCREEN';
  static const USERHOMESCREEN = '/USERHOMESCREEN';
  static const CHOOSEREPORTSCREEN = '/CHOOSEREPORTSCREEN';
  static const FINANCIALREPORTSCREEN = '/FINANCIALREPORTSCREEN';
  static const MERCHANTREGISTERACCOUNT = '/MERCHANTREGISTERACCOUNT';
  static const DEBTDETAILSSCREEN = '/DEBTDETAILSSCREEN';
  static const STOREFINREPORTSCREEN = '/STOREFINREPORTSCREEN';
  static const STOREREPORTSSCREEN = '/STOREREPORTSSCREEN';
  static const WALLETMANAGEMENT = '/WALLETMANAGEMENT';
  static const ADDWALLET = '/ADDWALLET';
}
