// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCfjrR0Jm90ltgX3pBT40bLmy0X7wpD1o',
    appId: '1:782864682414:web:4790e305aec818011e4c3f',
    messagingSenderId: '782864682414',
    projectId: 'yemen-soft-d1a17',
    authDomain: 'yemen-soft-d1a17.firebaseapp.com',
    storageBucket: 'yemen-soft-d1a17.appspot.com',
    measurementId: 'G-EYBRR83K8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpo9Ig979MU98A4sfZC-Wm0b-LU5Sm9GE"',
    appId: '1:191527608669:android:86c9b34fe4c2b6d15248b4',
    messagingSenderId: '191527608669',
    projectId: 'dion-440d5',
    storageBucket: 'yemen-soft-d1a17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZfv1HlS3O01GY8E7gSEX7lXw5rvNj7VQ',
    appId: '1:782864682414:ios:933e65ef5ed880fe1e4c3f',
    messagingSenderId: '782864682414',
    projectId: 'yemen-soft-d1a17',
    storageBucket: 'yemen-soft-d1a17.appspot.com',
    iosClientId:
        '782864682414-gkmcus8nof3i8qv5716moq132em6mgns.apps.googleusercontent.com',
    iosBundleId: 'com.example.yemenSoft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZfv1HlS3O01GY8E7gSEX7lXw5rvNj7VQ',
    appId: '1:782864682414:ios:933e65ef5ed880fe1e4c3f',
    messagingSenderId: '782864682414',
    projectId: 'yemen-soft-d1a17',
    storageBucket: 'yemen-soft-d1a17.appspot.com',
    iosClientId:
        '782864682414-gkmcus8nof3i8qv5716moq132em6mgns.apps.googleusercontent.com',
    iosBundleId: 'com.example.yemenSoft',
  );
}
